pub(crate) use windows_sys::Win32::System::SystemServices::{
    GUID_ADAPTIVE_POWER_BEHAVIOR_SUBGROUP, GUID_BATTERY_SUBGROUP, GUID_DISK_SUBGROUP,
    GUID_ENERGY_SAVER_SUBGROUP, GUID_GRAPHICS_SUBGROUP, GUID_IDLE_RESILIENCY_SUBGROUP,
    GUID_INTSTEER_SUBGROUP, GUID_PCIEXPRESS_SETTINGS_SUBGROUP, GUID_PROCESSOR_SETTINGS_SUBGROUP,
    GUID_SLEEP_SUBGROUP, GUID_SYSTEM_BUTTON_SUBGROUP, NO_SUBGROUP_GUID,
};
